---
# file: deploy.yml
- hosts: web
  sudo: yes
  roles:
      - { role: EHER.package_client, eher_package_name: 'chegamos' }
      - { role: EHER.package_client, eher_package_name: 'eher' }
      - { role: EHER.package_client, eher_package_name: 'meublog' }
      - { role: EHER.package_client, eher_package_name: 'paginasbrancas' }
      - { role: EHER.package_client, eher_package_name: 'queroservoluntario' }
      - { role: EHER.package_client, eher_package_name: 'papainoelexistemesmo' }
      - { role: EHER.package_client, eher_package_name: 'helena' }

