---
# file: mysql_snapshot_create.yml
- hosts: mysql
  roles:
    - role: EHER.mysql_snapshot
      eher_mysql_snapshot_action: create
      eher_mysql_snapshot_name: queroservoluntario
      eher_mysql_snapshot_database: queroservoluntario

