---
# file: mysql_snapshot_restore.yml
- hosts: mysql
  sudo: yes
  roles:
    - role: EHER.mysql_snapshot
      eher_mysql_snapshot_action: restore
      eher_mysql_snapshot_name: queroservoluntario
      eher_mysql_snapshot_database: queroservoluntario
      eher_mysql_username: root
      eher_mysql_password: "{{ mysql_root_password }}"
