---
- hosts: webservers
  sudo: yes
  tasks:
    - name: ensure ondrej/php5 repository is registered
      action: apt_repository repo=ppa:ondrej/php5

    - name: ensure nginx repository is registered
      action: apt_repository repo=ppa:nginx/stable

    - name: update apt repository cache is updated
      action: apt update_cache=yes

    - name: ensure php is installed
      action: apt pkg=php5 force=yes

    - name: ensure nginx is installed
      action: apt pkg=nginx

    - name: ensure apache2 is stopped
      action: service name=apache2 state=stopped

    - name: ensure apache2 is absent
      action: apt pkg=apache2 purge=yes

    - name: ensure nginx is running
      action: service name=nginx state=started
