---
- hosts: all
  sudo: yes
  tasks:
    - name: ensure apt cache is updated
      action: apt update_cache=yes

    - name: ensure software-properties-common is installed
      action: apt pkg=software-properties-common force=yes

    - name: ensure python-software-properties is installed
      action: apt pkg=python-software-properties force=yes

- hosts: web
  sudo: yes
  tasks:
    - name: ensure ondrej/php5 repository is registered
      action: apt_repository repo=ppa:ondrej/php5

    - name: ensure nginx repository is registered
      action: apt_repository repo=ppa:nginx/stable

    - name: ensure apt cache is updated
      action: apt update_cache=yes

    - name: ensure php is installed
      action: apt pkg=php5 force=yes

    - name: ensure php-curl is installed
      action: apt pkg=php5-curl force=yes

    - name: ensure git is installed
      action: apt pkg=git

    - name: ensure nginx is installed
      action: apt pkg=nginx

    - name: ensure apache2 is stopped
      action: service name=apache2 state=stopped

    - name: ensure apache2 is absent
      action: apt pkg=apache2 purge=yes

    - name: ensure nginx is running
      action: service name=nginx state=started

- hosts: package
  sudo: yes
  tasks:
    - name: ensure ondrej/php5 repository is registered
      action: apt_repository repo=ppa:ondrej/php5

    - name: ensure nginx repository is registered
      action: apt_repository repo=ppa:nginx/stable

    - name: ensure apt cache is updated
      action: apt update_cache=yes

    - name: ensure php is installed
      action: apt pkg=php5 force=yes

    - name: ensure php-curl is installed
      action: apt pkg=php5-curl force=yes

    - name: ensure build-essential is installed
      action: apt pkg=build-essential

    - name: ensure debhelper is installed
      action: apt pkg=debhelper

    - name: ensure dpkg-dev is installed
      action: apt pkg=dpkg-dev

    - name: ensure ruby is installed
      action: apt pkg=ruby

    - name: ensure ruby-dev is installed
      action: apt pkg=ruby-dev

    - name: ensure rubygems is installed
      action: apt pkg=rubygems

    - name: ensure fpm gem is installed
      action: gem name=fpm state=latest

- hosts: git
  sudo: yes
  tasks:
    - name: ensure git is installed
      action: apt pkg=git

    - name: ensure git user exists
      action: user name=git shell=/usr/bin/git-shell home=/home/git generate_ssh_key=yes

    - name: ensure authorized_keys exists
      action: copy src=files/home/git/.ssh/authorized_keys dest=/home/git/.ssh/authorized_keys owner=git mode=0600

    - name: ensure test-repo directory exists
      action: file path=/home/git/test-repo.git owner=git group=git mode=0775 state=directory

    - name: create test-repo repository
      action: command chdir=/home/git/test-repo.git creates=/home/git/test-repo.git/HEAD git init --bare

    - name: ensure test-repo permisions
      action: command chdir=/home/git/test-repo.git chown git.git -R .

    - name: ensure test-repo post-receive hook exists
      action: copy src=files/home/git/test-repo.git/hooks/post-receive dest=/home/git/test-repo.git/hooks/post-receive owner=git mode=0755

- hosts: web
  sudo: yes
  tasks:
    - name: ensure queroservoluntario.com configuration is present
      action: copy src=files/etc/nginx/sites-available/queroservoluntario.com dest=/etc/nginx/sites-available/queroservoluntario.com owner=root group=root mode=0644

    - name: ensure queroservoluntario.com is enabled
      action: file src=/etc/nginx/sites-available/queroservoluntario.com dest=/etc/nginx/sites-enabled/queroservoluntario.com state=link

    - name: ensure packages directory exists
      action: file path=/var/www/packages owner=git group=git mode=0775 state=directory

    - name: ensure packages configuration is present
      action: copy src=files/etc/nginx/sites-available/packages dest=/etc/nginx/sites-available/packages owner=root group=root mode=0644

    - name: ensure packages is enabled
      action: file src=/etc/nginx/sites-available/queroservoluntario.com dest=/etc/nginx/sites-enabled/queroservoluntario.com state=link

    - name: ensure nginx is running
      action: service name=nginx state=reloaded
