---
- hosts: webservers
  sudo: yes
  tasks:
    - name: ensure ondrej/php5 repository is registered
      action: apt_repository repo=ppa:ondrej/php5

    - name: ensure nginx repository is registered
      action: apt_repository repo=ppa:nginx/stable

    - name: ensure apt cache is updated
      action: apt update_cache=yes

    - name: ensure php is installed
      action: apt pkg=php5 force=yes

    - name: ensure php-curl is installed
      action: apt pkg=php5-curl force=yes

    - name: ensure git is installed
      action: apt pkg=git

    - name: ensure nginx is installed
      action: apt pkg=nginx

    - name: ensure apache2 is stopped
      action: service name=apache2 state=stopped

    - name: ensure apache2 is absent
      action: apt pkg=apache2 purge=yes

    - name: ensure queroservoluntario.com configuration is present
      action: copy src=files/etc/nginx/sites-available/queroservoluntario.com dest=/etc/nginx/sites-available/queroservoluntario.com owner=root group=root mode=0644

    - name: ensure queroservoluntario.com is enabled
      action: file src=/etc/nginx/sites-available/queroservoluntario.com dest=/etc/nginx/sites-enabled/queroservoluntario.com state=link

    - name: ensure nginx is running
      action: service name=nginx state=started

- hosts: deployservers
  sudo: yes
  tasks:
    - name: ensure ondrej/php5 repository is registered
      action: apt_repository repo=ppa:ondrej/php5

    - name: ensure nginx repository is registered
      action: apt_repository repo=ppa:nginx/stable

    - name: ensure apt cache is updated
      action: apt update_cache=yes

    - name: ensure php is installed
      action: apt pkg=php5 force=yes

    - name: ensure php-curl is installed
      action: apt pkg=php5-curl force=yes

    - name: ensure build-essential is installed
      action: apt pkg=build-essential

    - name: ensure debhelper is installed
      action: apt pkg=debhelper

- hosts: gitservers
  sudo: yes
  tasks:
    - name: ensure apt cache is updated
      action: apt update_cache=yes

    - name: ensure git is installed
      action: apt pkg=git

    - name: ensure git user exists
      action: user name=git shell=/usr/bin/git-shell home=/home/git generate_ssh_key=yes

    - name: ensure authorized_keys exists
      action: copy src=files/home/git/.ssh/authorized_keys dest=/home/git/.ssh/authorized_keys owner=git mode=0600

    - name: ensure test-repo directory exists
      action: file path=/home/git/test-repo.git owner=git group=git mode=0775 state=directory

    - name: create test-repo repository
      action: command chdir=/home/git/test-repo.git creates=/home/git/test-repo.git/HEAD git init --bare

    - name: ensure test-repo permisions
      action: command chdir=/home/git/test-repo.git chown git.git -R .

    - name: ensure test-repo update hook exists
      action: copy src=files/home/git/test-repo.git/hooks/update dest=/home/git/test-repo.git/hooks/update owner=git mode=0755

