---
# file: site.yml
- hosts: all
  sudo: yes
  tags: common
  roles:
    - common

- hosts: git
  sudo: yes
  tags: git
  roles:
    - git

- hosts: package
  sudo: yes
  tags: package
  roles:
    - package

- hosts: web
  sudo: yes
  tags: web
  roles:
    - web

