#!/bin/bash

rm -rf /tmp/builds/test-repo
mkdir -p /tmp/builds/test-repo

cd /tmp/builds
git clone /home/git/test-repo.git
cd test-repo

if [ -f Makefile ];
then
    make config install deb
fi
mv *.deb /var/www/packages

cd /var/www/packages
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
