---
- name: ensure deploy packages are available
  action: shell pack_{{ eher_package_name }}.sh > /var/www/packages/{{ eher_package_name }}.log creates=/var/www/packages/{{ eher_package_name }}.log

- name: ensure deploy debian channel is updated
  action: shell dpkg-scanpackages -m . /dev/null | gzip -9c > Packages.gz chdir=/var/www/packages

- name: ensure Packages.gz is writable by everyone
  action: file path=/var/www/packages/Packages.gz mode=0777 state=file

- name: ensure localhost apt software channel is configured
  action: apt_repository repo="deb http://{{ eher_package_server_name }}:{{ eher_package_port }} /" state=present

- name: ensure localhost apt-src software channel is absent
  action: apt_repository repo="deb http://{{ eher_package_server_name }}:{{ eher_package_port }} /" state=absent

- name: ensure apt cache is updated
  action: apt update_cache=yes

- name: ensure packages are deployed and updated
  action: apt pkg={{ eher_package_name }} state=latest force=yes

