---
- name: ensure nginx configuration
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  tags: config

  # Bug: it duplicates the line
- name: ensure php timezone is configured
  action: lineinfile dest={{ item }} state=present line='date.timezone = GMT' regexp='/date.timezone\ *=/'
  with_items:
    - /etc/php5/cli/php.ini
    - /etc/php5/fpm/php.ini
  tags: config

  # Bug: it duplicates the line
- name: ensure php version is hiden
  action: lineinfile dest={{ item }} state=present line='expose_php = off' regexp='/expose_php\ *=/'
  with_items:
    - /etc/php5/cli/php.ini
    - /etc/php5/fpm/php.ini
  tags: config

- name: ensure nginx is reloaded
  action: service name=nginx state=reloaded
  tags: config
