---
- name: ensure deploy debian channel is updated
  action: shell dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz chdir=/var/www/packages
  tags: deploy

- name: ensure localhost apt software channel is configured
  action: apt_repository repo='deb {{ deploy_debian_channel }}' state=present
  tags: deploy

- name: ensure localhost apt-src software channel is absent
  action: apt_repository repo='deb-src {{ deploy_debian_channel }}' state=absent

- name: ensure apt cache is updated
  action: apt update_cache=yes
  tags: deploy

- name: ensure packages are deployed and updated
  action: apt pkg={{ item }} state=latest force=yes
  with_items: deploy_packages
  tags: deploy
