---
- name: ensure repositories are registered
  action: apt_repository repo={{ item }}
  with_items: 
    - ppa:ondrej/php5
    - ppa:nginx/stable
  tags: install

- name: ensure apt cache is updated
  action: apt update_cache=yes
  tags: install

- name: remove apache if installed
  apt: pkg=apache2 state=absent
  tags: install

- name: ensure packages are installed
  action: apt pkg={{ item }} force=yes
  with_items:
    - php5
    - php5-cli
    - php5-apcu
    - php5-curl
    - php5-intl
    - php5-mysql
    - php5-sqlite
    - php5-fpm
    - nginx
  tags: install

- name: ensure nginx is running
  action: service name=nginx state=started
  tags: install
