---
- name: ensure that repositories are registered
  action: apt_repository repo={{ item }}
  with_items:
    - ppa:ondrej/php5
    - ppa:nginx/stable

- name: ensure apt cache is updated
  action: apt update_cache=yes

- name: ensure that packages are installed
  action: apt pkg={{ item }} force=yes
  with_items:
    - php5
    - php5-curl
    - build-essential
    - debhelper
    - dpkg-dev
    - ruby
    - ruby-dev
    - rubygems

- name: ensure fpm gem is installed
  action: gem name=fpm state=latest

