---
- name: ensure that repositories are registered
  action: apt_repository repo={{ item }}
  with_items:
    - ppa:ondrej/php5
    - ppa:nginx/stable

- name: ensure apt cache is updated
  action: apt update_cache=yes

- name: ensure that packages are installed
  action: apt pkg={{ item }} force=yes
  with_items:
    - php5
    - php5-curl
    - build-essential
    - debhelper
    - dpkg-dev
    - ruby
    - ruby-dev
    - rubygems

- name: ensure fpm gem is installed
 #action: gem name=fpm user_install=no state=latest
  action: command gem install fpm creates=/usr/local/bin/fpm

- name: ensure packages build directory exists
  action: file path={{ build_path }} mode=0777 state=directory

- name: ensure package script
  action: template src=pack.sh.j2 dest=/usr/local/bin/pack.sh mode=0755
